### PR TITLE
Postprocessing Framework

### PR DESCRIPTION
**Pull request by TheIceCreamBear**
Framework for post-processing. Allows for gaussian blur, combining two outputs, and adds custom MSAA (4x).

For another PR:
- [ ] Pull bright info from scene 
- [ ] Apply blurred bloom to scene

### CODE REVIEW

**Review by ctcuff — COMMENTED** [review]
Code looks great! Can you merge `master` into this branch? Looks like this is still using an older version

**Comment by TheIceCreamBear** [comment]
> Code looks great! Can you merge `master` into this branch? Looks like this is still using an older version

Done.

**Review by ctcuff — APPROVED** [review]
LGTM

**Review by Armintron — APPROVED** [review]
Looks good to me! Might need to do a `npm run format` though.

**Comment by TheIceCreamBear** [comment]
2 approvals plus code formatted. Merging.

**Pull request merged**
