### PR TITLE
File cleanup

### PR DESCRIPTION
**Pull request by Armintron**
This PR greatly reduces loading times.
- Gets rid of unused models / textures
- Convert `models` folder to `assets`, which have self-contained folders for each "asset" (rayman, cow, asteroid, etc)
- Converted to lower res textures where possible

### CODE REVIEW

**Review by ctcuff — APPROVED** [review]
LGTM but I think we can remove the assets we aren't using, like `rayman`, `cow`, and `tie_fighter`

**Comment by Armintron** [comment]
> LGTM but I think we can remove the assets we aren't using, like `rayman`, `cow`, and `tie_fighter`

I only left them because we might want to use them later on and it doesnt really hurt to leave them. Delete them if youd like 👍

**Comment by ctcuff** [comment]
> > LGTM but I think we can remove the assets we aren't using, like `rayman`, `cow`, and `tie_fighter`
> 
> I only left them because we might want to use them later on and it doesnt really hurt to leave them. Delete them if youd like 👍

Ah, if that's the case, we can keep the assets just in case, but we only need to load what we're using, so we don't need to load rayman in `index.js`

**Comment by Armintron** [comment]
> > > LGTM but I think we can remove the assets we aren't using, like `rayman`, `cow`, and `tie_fighter`
> > 
> > 
> > I only left them because we might want to use them later on and it doesnt really hurt to leave them. Delete them if youd like 👍
> 
> Ah, if that's the case, we can keep the assets just in case, but we only need to load what we're using, so we don't need to load rayman in `index.js`

Sounds like a plan

**Pull request merged**
